import { z } from "zod";

/*
  Attendee submission boundary. Validated server-side in submitAttendance.
  Identity is self-reported (no login); the token gates access to the course.

  Note: z.guid() is used for the token field (instead of z.uuid()) because
  Zod v4 enforces strict RFC 4122 variant bits in z.uuid(), which rejects
  all-hex UUIDs like "11111111-1111-1111-1111-111111111111". z.guid() accepts
  any well-formed 8-4-4-4-12 hex pattern, which is appropriate here since
  tokens are generated by Supabase/Prisma and may not be strict RFC 4122.
*/

export const attendeeAnswerSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("TF"), answer: z.enum(["True", "False"]) }),
  z.object({ type: z.literal("MC"), answer: z.number().int().min(0).max(3) }),
]);

export const attendeeSubmissionSchema = z.object({
  token: z.guid(),
  attendeeName: z.string().min(2).max(200),
  attendeeEmail: z.string().email().max(200),
  licenseNumber: z.string().max(100).optional(),
  licenseType: z.string().max(100).optional(),
  licenseStates: z.array(z.string().length(2)).min(1).max(10),
  affirmed: z.literal(true),
  answers: z.array(attendeeAnswerSchema).length(5),
});

export type AttendeeSubmission = z.infer<typeof attendeeSubmissionSchema>;
